### ISSUE TITLE
[1.19.2] Swapping blocks with leaves makes them decay over time

### ISSUE THREAD

**Issue by Hiconel** [tinytransfem/Block_Swapper#1] opened 2022-10-09 13:01 UTC
When you swap a block with a leaf block, the leaves start to decay over time, because they are not marked as persistent.

This could be intented behaviour, but I would expect any blocks being placed by the block swapper to act as if they were placed by a player.

**Comment by tinytransfem** [comment] 2022-10-09 16:03
This is very much not intended behavior, it's an oversight on my part

**Comment by tinytransfem** [comment] 2023-09-18 13:16
almost a year later because I somehow never ended up publishing the file, but this is now fixed in version 2.0

**Closed as completed by tinytransfem** 2023-09-18 13:16 UTC
Labels: bug, being worked on
